# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# Force disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ExpenseTracker' do
  config = use_native_modules!

  # React Native Vector Icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix for Xcode 15+ and iOS 17+
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end

    # Copy react-native-vector-icons fonts to app bundle
    app_target = installer.aggregate_targets.find { |target| target.name == 'Pods-ExpenseTracker' }
    if app_target
      fonts_dir = File.join(__dir__, '..', 'node_modules', 'react-native-vector-icons', 'Fonts')
      app_fonts_dir = File.join(__dir__, 'ExpenseTracker', 'Fonts')
      FileUtils.mkdir_p(app_fonts_dir)
      Dir.glob(File.join(fonts_dir, '*.ttf')).each do |font|
        FileUtils.cp(font, app_fonts_dir)
      end
    end
  end
end
